### ISSUE TITLE
Git commands not working

### ISSUE THREAD

**Issue by senavailable** [githubteacher/developers-jan-2016#65]
sarumugam@MPKL13fdc5449:~/developers-jan-2016$ git commit

This command opens vi editor with below 

```
# Please enter the commit message for your changes. Lines starting
# with '#' will be ignored, and an empty message aborts the commit.
# On branch senavailable-edits
# Your branch is up-to-date with 'origin/senavailable-edits'.
#
# Changes to be committed:
#       modified:   senavailable.md
#
# Changes not staged for commit:
#       modified:   senavailable.md
```

Once I come out of vi, I see below message:

sarumugam@MPKL13fdc5449:~/developers-jan-2016$ git commit
Aborting commit due to empty commit message.

I have below setting:
sarumugam@MPKL13fdc5449:~/developers-jan-2016$ git config core.editor
vi

**Comment by githubteacher** [comment]
@senavailable the command is configured correctly, but you'll need to add a message to your commit -- the lines that start `#` are comments and don't count. You can add anything, but if you save/exit the editor with _only_ comments, git will assume you are canceling the commit.

**Comment by senavailable** [comment]
:+1:
